version: '3.12'

services:

  telegram-bot:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    env_file:
      - ./.env
    container_name: "deutch_bot"
    restart: always
    volumes:
      - ./:/app
    links:
      - mongo_db
    depends_on:
      - mongo_db
    networks:
      - bot_network

  mongo_db:
    image: mongo
    container_name: "mongo_db"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    restart: always
    networks:
      - bot_network

networks:
    bot_network: